# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hello.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x05hello\x1a\x1bgoogle/protobuf/empty.proto\"6\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\x1b\n\rUserIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"E\n\tUserReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\",\n\tUsersList\x12\x1f\n\x05users\x18\x01 \x03(\x0b\x32\x10.hello.UserReply2\x95\x02\n\x0bUserService\x12\x32\n\nCreateUser\x12\x12.hello.UserRequest\x1a\x10.hello.UserReply\x12\x31\n\x07GetUser\x12\x14.hello.UserIdRequest\x1a\x10.hello.UserReply\x12\x32\n\nUpdateUser\x12\x12.hello.UserRequest\x1a\x10.hello.UserReply\x12\x34\n\nDeleteUser\x12\x14.hello.UserIdRequest\x1a\x10.hello.UserReply\x12\x35\n\tListUsers\x12\x16.google.protobuf.Empty\x1a\x10.hello.UsersListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=51
  _globals['_USERREQUEST']._serialized_end=105
  _globals['_USERIDREQUEST']._serialized_start=107
  _globals['_USERIDREQUEST']._serialized_end=134
  _globals['_USERREPLY']._serialized_start=136
  _globals['_USERREPLY']._serialized_end=205
  _globals['_USERSLIST']._serialized_start=207
  _globals['_USERSLIST']._serialized_end=251
  _globals['_USERSERVICE']._serialized_start=254
  _globals['_USERSERVICE']._serialized_end=531
# @@protoc_insertion_point(module_scope)
